---
  # Creating AWS EC2 Instances...
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - ec2secret/aws-creds.yml
  vars:
    wordpress_ip: 52.51.150.252
    elk_ip: 34.251.177.202
    keypair: satya_key_pair
    instance_type: t2.micro
    image: ami-1e749f67
    region: eu-west-1
  tasks:
  - name: create wordpress security group
    ec2_group:
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        name: "wordpress_sg"
        description: "wordpress security group"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        register: ec2wpsg

  - name: Print all sg variables
    debug: var=ec2wpsg

  - name: Launch wordpress instance
    ec2:
        key_name: "{{ keypair }}"
        group_id: "{{ ec2wpsg.group_id }}"
        count: 1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
            Name: wordpress
            Env: dev
    register: ec2wp

  - name: Print all ec2 variables
    debug: var=ec2wp

  - name: Assign ip to wordpress
    ec2_eip:
        region: "{{ region }}"
        device_id: "{{ item }}"
        ip: "{{ wordpress_ip }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
    with_items: "{{ ec2wp.instance_ids }}"

  - name: create elk security group
    ec2_group:
        region: "{{ region }}"
		aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        name: "elk_sg"
        description: "elk security group"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    register: ec2elksg

  - name: Print all sg variables
    debug: var=ec2elksg

  - name: Launch elk instance
    ec2:
         key_name: "{{ keypair }}"
         group_id: "{{ ec2wpsg.group_id }}"
         count: 1
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
            Name: elk
            Env: dev
    register: ec2elk

  - name: Assign ip to ELK
    ec2_eip:
        region: "{{ region }}"
        device_id: "{{ item }}"
        ip: "{{ elk_ip }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
    with_items: "{{ ec2elk.instance_ids }}"

