version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - "10.0.15.40:8080:80"
    
    volumes:
      - ./code:/code
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .database:/var/lib/mysql
